[pg-primary]
description = "PostgreSQL Primary Demo"
conninfo = host=pg-primary port=5432 user=barman dbname=postgres password=barman_demo_password
streaming_conninfo = host=pg-primary port=5432 user=barman password=barman_demo_password
backup_method = postgres
streaming_archiver = on
archiver = off
slot_name = barman
create_slot = auto
backup_options = concurrent_backup
retention_policy = REDUNDANCY 2
